# Generated by Django 5.2.8 on 2025-11-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_ticket_user_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
