# Generated by Django 5.2.8 on 2025-11-27 05:26

import event.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_seats_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True, validators=[event.models.event.not_past]),
        ),
    ]
