# Generated by Django 5.2.8 on 2025-11-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
